drop database if exists caffe;
create database caffe;
use caffe;

CREATE TABLE crew (
  crewId INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  email VARCHAR(50) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  phoneNumber INT NOT NULL,
  bio VARCHAR(100),
  myPageImg VARCHAR(500),
  profileImage VARCHAR(500),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE review (
  reviewId INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  representImage VARCHAR(500),
  content LONGTEXT NOT NULL,
  likeNum INT,
  writtenBy INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (writtenBy) REFERENCES crew(crewId) ON DELETE CASCADE
);
